// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChg9uJMabHUJtV0K68036kzyDpPlIQzAo',
    appId: '1:86451927015:web:08d760df53bb2fd8676f42',
    messagingSenderId: '86451927015',
    projectId: 'recontheact-ai',
    authDomain: 'recontheact-ai.firebaseapp.com',
    storageBucket: 'recontheact-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_dgPn-cOp8CHoU3Pz-P8vmLJRJF4yP_o',
    appId: '1:86451927015:android:fcfb72deab8dabb3676f42',
    messagingSenderId: '86451927015',
    projectId: 'recontheact-ai',
    storageBucket: 'recontheact-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qnjTNnJlC3CKA42WRVTqAxcDs1N2iJo',
    appId: '1:86451927015:ios:e3b4514bf69c459d676f42',
    messagingSenderId: '86451927015',
    projectId: 'recontheact-ai',
    storageBucket: 'recontheact-ai.appspot.com',
    iosBundleId: 'com.example.recognizemeIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_qnjTNnJlC3CKA42WRVTqAxcDs1N2iJo',
    appId: '1:86451927015:ios:e8cf7085b4ca3590676f42',
    messagingSenderId: '86451927015',
    projectId: 'recontheact-ai',
    storageBucket: 'recontheact-ai.appspot.com',
    iosBundleId: 'com.example.recognizemeIa.RunnerTests',
  );
}
